<?php

namespace Database\Seeders;

use App\Models\Basic\Facility\Facility;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Facility_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $facilitys = [

            [
                'id' => 1,
                'department_id' => 1,
                'facility_parent_id' => 1,
                'facility_type_id' => 1,
                'counting_number' => 1234567,
                'name' => 'الوزارة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,

            ], [

                'id' => 2,
                'department_id' => 1,
                'facility_parent_id' => 1,
                'facility_type_id' => 2,
                'counting_number' => 1234567,
                'name' => 'مكتب المدير العام',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,

            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 3,
                'counting_number' => 1234567,
                'name' => 'المعاون الاداري',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 4,
                'counting_number' => 1234567,
                'name' => 'المعاون الفني',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الاشراف الاختصاصي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الاشراف التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم محو الامية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الامتحانات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم التخطيط التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم النشاط الرياضي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الاعداد والتدريب',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم شؤون المناهج',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم التعليم المهني',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم التعليم العام والملاك',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الشؤون المالية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الموارد البشرية ',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم الادارة والتجهيزات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم تربية الكوفة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم تربية المناذرة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 3,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'قسم التربية الكردية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الرقابة والتدقيق التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الاعلام التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة العقود',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ادارة الجودة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المتابعة والقلم',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الشؤون القانونية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التعليم عن بعد',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 8,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الشهادات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 8,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الامتحانات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 8,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => ' شعبة التقويم',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 8,
                'facility_type_id' => 2,
                'counting_number' => 1234567,
                'name' => 'شعبة التدقيق وصحة الصدور',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [

                'department_id' => 1,
                'facility_parent_id' => 8,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة شؤون الطلبة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
            //////////////////////////////////////////////////// قسم التخطيط التربوي //////////////////////////////////////////////////////////////////
            , [
                'department_id' => 1,
                'facility_parent_id' => 9,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التخطيط التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 9,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الاحصاء',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 9,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المتابعة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 9,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المعلومات والاتصالات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
            //////////////////////////////////////////////////// قسم النشاط الرياضي //////////////////////////////////////////////////////////////////

            , [
                'department_id' => 1,
                'facility_parent_id' => 10,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الرياضة المدرسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 10,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التربية الكشفية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 10,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة النشاط المدرسي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 10,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة البيئة والصحة المدرسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
            //////////////////////////////////////////////////// قسم الاعداد والتدريب //////////////////////////////////////////////////////////////////
            , [
                'department_id' => 1,
                'facility_parent_id' => 11,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المعاهد',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 11,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الاشغال اليدوية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 11,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة البحوث والدراسات التربوية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 11,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التدريب',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
            //////////////////////////////////////////////////// قسم شؤون المناهج والتقنيات التربوية //////////////////////////////////////////////////////////////////
            , [
                'department_id' => 1,
                'facility_parent_id' => 12,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المناهج والمكتبات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 12,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التقنيات التعليمية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 12,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة مناهج الحاسوب',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
            //////////////////////////////////////////////////// قسم التعليم المهني //////////////////////////////////////////////////////////////////

            , [
                'department_id' => 1,
                'facility_parent_id' => 13,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الادارة والتجهيزات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 13,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'الشعبة العلمية والمهنية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            [
                'department_id' => 1,
                'facility_parent_id' => 13,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة شؤون الطلبة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            [
                'department_id' => 1,
                'facility_parent_id' => 13,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الاشراف',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            //////////////////////////////////////////////////// قسم الامتحانات //////////////////////////////////////////////////////////////////

            [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ملاك الابتدائي ورياض الاطفال',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ملاك الثانوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ملاك الموظفين',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الارشاد والبطاقة المدرسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التعليم الاهلي والاجنية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التربية الخاصة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الادارة المدرسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            //////////////////////////////////////////////////// قسم الشؤون المالية //////////////////////////////////////////////////////////////////
            [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التنظيم والموازنة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة رواتب الابتدائي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة رواتب الثانوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ديوان المديرية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة امانة الصندوق',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الصرف',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 14,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الحوانيت',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            //////////////////////////////////////////////////// قسم الموارد البشرية //////////////////////////////////////////////////////////////////
            [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ذاتية الابتدائي والاطفال',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ذاتية الثانوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة ذاتية الموظفين',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التقاعد ودعم ذوي الشهداء',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة العلاوات والترقيات والملفات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            //////////////////////////////////////////////////// قسم الادارة والتجهيزات //////////////////////////////////////////////////////////////////
            [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الصادرة والواردة والطبع ',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الارشيف والهويات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الخدمات والاستعلامات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة السيارات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة تجهيزات الكتب',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة تجهيزات القرطاسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة تجهيزات الاثاث',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],

            //////////////////////////////////////////////////// قسم تربية الكوفة  //////////////////////////////////////////////////////////////////

            [
                'department_id' => 1,
                'facility_parent_id' => 18,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'الشعبة الادارية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 18,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'الشعبة الفنية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 18,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الحسابات والمالية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 18,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التخطيط',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 18,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة محو الامية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],

            //////////////////////////////////////////////////// قسم تربية المناذرة  //////////////////////////////////////////////////////////////////

            [
                'department_id' => 1,
                'facility_parent_id' => 19,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'الشعبة الادارية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 19,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'الشعبة الفنية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 19,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الحسابات والمالية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 19,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة التخطيط',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 19,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة محو الامية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],

            //////////////////////////////////////////////////// قسم الدراسة الكردية //////////////////////////////////////////////////////////////////

            [
                'department_id' => 1,
                'facility_parent_id' => 20,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة المناهج والكتب',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 20,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الهيئات النعليمية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 4,
                'facility_type_id' => 6,
                'counting_number' => 1234567,
                'name' => 'شعبة الاملاك والاراضي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],


            //////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
            //////////////////////////////////////////////////// الوحدات //////////////////////////////////////////////////////////////////
            //////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////

            [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة التصاريح والمعلومات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],  [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة التقاطع الوظيفي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],  [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة الخدمة الفرعية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],  [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة المفتش التربوي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],  [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة شؤون المواطنين',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ],
            [
                'department_id' => 1,
                'facility_parent_id' => 9,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة تمكين المرأة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 13,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة الرقابة والتدقيق الداخلي',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة تنفيذ خطة الاجازات الدراسية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 16,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة بنك المعلومات',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 17,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة الصيانة',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 34,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة نظام EMIS',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 44,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة اللغة العربية',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 90,
                'facility_type_id' => 7,
                'counting_number' => 1234567,
                'name' => 'وحدة الاستملاك والتبرع',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ], [
                'department_id' => 1,
                'facility_parent_id' => 2,
                'facility_type_id' => 5,
                'counting_number' => 1234567,
                'name' => 'مديرية النجف',
                'is_main_school' => 2,
                'url_address' => $this->get_random_string(60),
                'established_year' => 0,
                'duality_id' => 1,
                'main_section_id' => 2,
                'school_gender_id' => 1,
                'school_invironment_id' => 1,
                'school_property_id' => 1,
                'school_stage_id' => 1,
                'school_time_id' => 1,
                'province_id' => 1,
            ]
        ];
        foreach ($facilitys as $facility) {
            Facility::create($facility);
        }
    }
    function get_random_string($length)
    {
        $array = array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
        $text = "";
        $length = rand(22, $length);

        for ($i = 0; $i < $length; $i++) {
            $random = rand(0, 61);
            $text .= $array[$random];
        }
        return $text;
    }
}
